server:
  port: 9000
spring:
  author: Nanf_bunan
  application:
    name: Govern
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/governroom?useUnicode=true&characterEncoding=utf8
    username: root
    password: wytsw123321
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.govern.webservie.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  # 请求头
  tokenHeader: Authorization
  # 签名加盐
  secret: governmanager
  # jwt过期时间
  expiration: 7200
  # token头部
  tokenHead: 'Bearer'
